// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: email.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type JobStatus int32

const (
	JobStatus_STATUS_UNKNOWN    JobStatus = 0
	JobStatus_STATUS_PENDING    JobStatus = 1
	JobStatus_STATUS_PROCESSING JobStatus = 2
	JobStatus_STATUS_COMPLETED  JobStatus = 3
	JobStatus_STATUS_FAILED     JobStatus = 4
	JobStatus_STATUS_CANCELLED  JobStatus = 5
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_PENDING",
		2: "STATUS_PROCESSING",
		3: "STATUS_COMPLETED",
		4: "STATUS_FAILED",
		5: "STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"STATUS_UNKNOWN":    0,
		"STATUS_PENDING":    1,
		"STATUS_PROCESSING": 2,
		"STATUS_COMPLETED":  3,
		"STATUS_FAILED":     4,
		"STATUS_CANCELLED":  5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_email_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_email_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0}
}

type JobPriority int32

const (
	JobPriority_PRIORITY_UNKNOWN JobPriority = 0
	JobPriority_PRIORITY_HIGH    JobPriority = 1
	JobPriority_PRIORITY_NORMAL  JobPriority = 2
	JobPriority_PRIORITY_LOW     JobPriority = 3
)

// Enum value maps for JobPriority.
var (
	JobPriority_name = map[int32]string{
		0: "PRIORITY_UNKNOWN",
		1: "PRIORITY_HIGH",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_LOW",
	}
	JobPriority_value = map[string]int32{
		"PRIORITY_UNKNOWN": 0,
		"PRIORITY_HIGH":    1,
		"PRIORITY_NORMAL":  2,
		"PRIORITY_LOW":     3,
	}
)

func (x JobPriority) Enum() *JobPriority {
	p := new(JobPriority)
	*p = x
	return p
}

func (x JobPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_email_proto_enumTypes[1].Descriptor()
}

func (JobPriority) Type() protoreflect.EnumType {
	return &file_email_proto_enumTypes[1]
}

func (x JobPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobPriority.Descriptor instead.
func (JobPriority) EnumDescriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{1}
}

// Email Job Management
type CreateEmailJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []string               `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string               `protobuf:"bytes,2,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []string               `protobuf:"bytes,3,rep,name=bcc,proto3" json:"bcc,omitempty"`
	TemplateName  string                 `protobuf:"bytes,4,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority      JobPriority            `protobuf:"varint,6,opt,name=priority,proto3,enum=email.JobPriority" json:"priority,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,7,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailJobRequest) Reset() {
	*x = CreateEmailJobRequest{}
	mi := &file_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailJobRequest) ProtoMessage() {}

func (x *CreateEmailJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailJobRequest.ProtoReflect.Descriptor instead.
func (*CreateEmailJobRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEmailJobRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *CreateEmailJobRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *CreateEmailJobRequest) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *CreateEmailJobRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *CreateEmailJobRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *CreateEmailJobRequest) GetPriority() JobPriority {
	if x != nil {
		return x.Priority
	}
	return JobPriority_PRIORITY_UNKNOWN
}

func (x *CreateEmailJobRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

type CreateEmailJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Job           *EmailJob              `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailJobResponse) Reset() {
	*x = CreateEmailJobResponse{}
	mi := &file_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailJobResponse) ProtoMessage() {}

func (x *CreateEmailJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailJobResponse.ProtoReflect.Descriptor instead.
func (*CreateEmailJobResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEmailJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateEmailJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateEmailJobResponse) GetJob() *EmailJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetEmailJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailJobRequest) Reset() {
	*x = GetEmailJobRequest{}
	mi := &file_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailJobRequest) ProtoMessage() {}

func (x *GetEmailJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailJobRequest.ProtoReflect.Descriptor instead.
func (*GetEmailJobRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmailJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetEmailJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Job           *EmailJob              `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailJobResponse) Reset() {
	*x = GetEmailJobResponse{}
	mi := &file_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailJobResponse) ProtoMessage() {}

func (x *GetEmailJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailJobResponse.ProtoReflect.Descriptor instead.
func (*GetEmailJobResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{3}
}

func (x *GetEmailJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetEmailJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEmailJobResponse) GetJob() *EmailJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type UpdateEmailJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending", "processing", "sent", "failed", "cancelled"
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SentAt        string                 `protobuf:"bytes,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"` // ISO 8601 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailJobStatusRequest) Reset() {
	*x = UpdateEmailJobStatusRequest{}
	mi := &file_email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailJobStatusRequest) ProtoMessage() {}

func (x *UpdateEmailJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailJobStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEmailJobStatusRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *UpdateEmailJobStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateEmailJobStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UpdateEmailJobStatusRequest) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

type UpdateEmailJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Job           *EmailJob              `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailJobStatusResponse) Reset() {
	*x = UpdateEmailJobStatusResponse{}
	mi := &file_email_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailJobStatusResponse) ProtoMessage() {}

func (x *UpdateEmailJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailJobStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmailJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEmailJobStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateEmailJobStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateEmailJobStatusResponse) GetJob() *EmailJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListEmailJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	JobType       string                 `protobuf:"bytes,2,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailJobsRequest) Reset() {
	*x = ListEmailJobsRequest{}
	mi := &file_email_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailJobsRequest) ProtoMessage() {}

func (x *ListEmailJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailJobsRequest.ProtoReflect.Descriptor instead.
func (*ListEmailJobsRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{6}
}

func (x *ListEmailJobsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListEmailJobsRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *ListEmailJobsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListEmailJobsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ListEmailJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEmailJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEmailJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Jobs          []*EmailJob            `protobuf:"bytes,3,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailJobsResponse) Reset() {
	*x = ListEmailJobsResponse{}
	mi := &file_email_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailJobsResponse) ProtoMessage() {}

func (x *ListEmailJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailJobsResponse.ProtoReflect.Descriptor instead.
func (*ListEmailJobsResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{7}
}

func (x *ListEmailJobsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListEmailJobsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListEmailJobsResponse) GetJobs() []*EmailJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListEmailJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListEmailJobsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEmailJobsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Email Templates
type GetEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailTemplateRequest) Reset() {
	*x = GetEmailTemplateRequest{}
	mi := &file_email_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailTemplateRequest) ProtoMessage() {}

func (x *GetEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{8}
}

func (x *GetEmailTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *GetEmailTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetEmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Template      *EmailTemplate         `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailTemplateResponse) Reset() {
	*x = GetEmailTemplateResponse{}
	mi := &file_email_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailTemplateResponse) ProtoMessage() {}

func (x *GetEmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetEmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{9}
}

func (x *GetEmailTemplateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetEmailTemplateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEmailTemplateResponse) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type ListEmailTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailTemplatesRequest) Reset() {
	*x = ListEmailTemplatesRequest{}
	mi := &file_email_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailTemplatesRequest) ProtoMessage() {}

func (x *ListEmailTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListEmailTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{10}
}

func (x *ListEmailTemplatesRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ListEmailTemplatesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEmailTemplatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEmailTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Templates     []*EmailTemplate       `protobuf:"bytes,3,rep,name=templates,proto3" json:"templates,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailTemplatesResponse) Reset() {
	*x = ListEmailTemplatesResponse{}
	mi := &file_email_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailTemplatesResponse) ProtoMessage() {}

func (x *ListEmailTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListEmailTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{11}
}

func (x *ListEmailTemplatesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListEmailTemplatesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListEmailTemplatesResponse) GetTemplates() []*EmailTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListEmailTemplatesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlContent   string                 `protobuf:"bytes,3,opt,name=html_content,json=htmlContent,proto3" json:"html_content,omitempty"`
	TextContent   string                 `protobuf:"bytes,4,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	Variables     string                 `protobuf:"bytes,5,opt,name=variables,proto3" json:"variables,omitempty"` // JSON array string
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailTemplateRequest) Reset() {
	*x = CreateEmailTemplateRequest{}
	mi := &file_email_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailTemplateRequest) ProtoMessage() {}

func (x *CreateEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{12}
}

func (x *CreateEmailTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetHtmlContent() string {
	if x != nil {
		return x.HtmlContent
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetVariables() string {
	if x != nil {
		return x.Variables
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateEmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Template      *EmailTemplate         `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailTemplateResponse) Reset() {
	*x = CreateEmailTemplateResponse{}
	mi := &file_email_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailTemplateResponse) ProtoMessage() {}

func (x *CreateEmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateEmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{13}
}

func (x *CreateEmailTemplateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateEmailTemplateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateEmailTemplateResponse) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type UpdateEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlContent   string                 `protobuf:"bytes,4,opt,name=html_content,json=htmlContent,proto3" json:"html_content,omitempty"`
	TextContent   string                 `protobuf:"bytes,5,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	Variables     string                 `protobuf:"bytes,6,opt,name=variables,proto3" json:"variables,omitempty"` // JSON array string
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailTemplateRequest) Reset() {
	*x = UpdateEmailTemplateRequest{}
	mi := &file_email_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailTemplateRequest) ProtoMessage() {}

func (x *UpdateEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateEmailTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetHtmlContent() string {
	if x != nil {
		return x.HtmlContent
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetVariables() string {
	if x != nil {
		return x.Variables
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateEmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Template      *EmailTemplate         `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailTemplateResponse) Reset() {
	*x = UpdateEmailTemplateResponse{}
	mi := &file_email_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailTemplateResponse) ProtoMessage() {}

func (x *UpdateEmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateEmailTemplateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateEmailTemplateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateEmailTemplateResponse) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// Email Tracking
type GetEmailTrackingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailTrackingRequest) Reset() {
	*x = GetEmailTrackingRequest{}
	mi := &file_email_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailTrackingRequest) ProtoMessage() {}

func (x *GetEmailTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailTrackingRequest.ProtoReflect.Descriptor instead.
func (*GetEmailTrackingRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{16}
}

func (x *GetEmailTrackingRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *GetEmailTrackingRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GetEmailTrackingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tracking      *EmailTracking         `protobuf:"bytes,3,opt,name=tracking,proto3" json:"tracking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailTrackingResponse) Reset() {
	*x = GetEmailTrackingResponse{}
	mi := &file_email_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailTrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailTrackingResponse) ProtoMessage() {}

func (x *GetEmailTrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailTrackingResponse.ProtoReflect.Descriptor instead.
func (*GetEmailTrackingResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{17}
}

func (x *GetEmailTrackingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetEmailTrackingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEmailTrackingResponse) GetTracking() *EmailTracking {
	if x != nil {
		return x.Tracking
	}
	return nil
}

type UpdateEmailTrackingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                              // "sent", "delivered", "bounced", "opened", "clicked"
	SentAt        string                 `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`                // ISO 8601 timestamp
	DeliveredAt   string                 `protobuf:"bytes,6,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"` // ISO 8601 timestamp
	OpenedAt      string                 `protobuf:"bytes,7,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`          // ISO 8601 timestamp
	ClickedAt     string                 `protobuf:"bytes,8,opt,name=clicked_at,json=clickedAt,proto3" json:"clicked_at,omitempty"`       // ISO 8601 timestamp
	BounceReason  string                 `protobuf:"bytes,9,opt,name=bounce_reason,json=bounceReason,proto3" json:"bounce_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailTrackingRequest) Reset() {
	*x = UpdateEmailTrackingRequest{}
	mi := &file_email_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailTrackingRequest) ProtoMessage() {}

func (x *UpdateEmailTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailTrackingRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailTrackingRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateEmailTrackingRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *UpdateEmailTrackingRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UpdateEmailTrackingRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *UpdateEmailTrackingRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateEmailTrackingRequest) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *UpdateEmailTrackingRequest) GetDeliveredAt() string {
	if x != nil {
		return x.DeliveredAt
	}
	return ""
}

func (x *UpdateEmailTrackingRequest) GetOpenedAt() string {
	if x != nil {
		return x.OpenedAt
	}
	return ""
}

func (x *UpdateEmailTrackingRequest) GetClickedAt() string {
	if x != nil {
		return x.ClickedAt
	}
	return ""
}

func (x *UpdateEmailTrackingRequest) GetBounceReason() string {
	if x != nil {
		return x.BounceReason
	}
	return ""
}

type UpdateEmailTrackingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tracking      *EmailTracking         `protobuf:"bytes,3,opt,name=tracking,proto3" json:"tracking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailTrackingResponse) Reset() {
	*x = UpdateEmailTrackingResponse{}
	mi := &file_email_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailTrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailTrackingResponse) ProtoMessage() {}

func (x *UpdateEmailTrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailTrackingResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmailTrackingResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateEmailTrackingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateEmailTrackingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateEmailTrackingResponse) GetTracking() *EmailTracking {
	if x != nil {
		return x.Tracking
	}
	return nil
}

// Health check
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_email_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{20}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_email_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{21}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Data structures
type EmailJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	To            []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string               `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []string               `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc,omitempty"`
	TemplateName  string                 `protobuf:"bytes,5,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        JobStatus              `protobuf:"varint,7,opt,name=status,proto3,enum=email.JobStatus" json:"status,omitempty"`
	Priority      JobPriority            `protobuf:"varint,8,opt,name=priority,proto3,enum=email.JobPriority" json:"priority,omitempty"`
	RetryCount    int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,10,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ProcessedAt   string                 `protobuf:"bytes,12,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	SentAt        string                 `protobuf:"bytes,13,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailJob) Reset() {
	*x = EmailJob{}
	mi := &file_email_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailJob) ProtoMessage() {}

func (x *EmailJob) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailJob.ProtoReflect.Descriptor instead.
func (*EmailJob) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{22}
}

func (x *EmailJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmailJob) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EmailJob) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *EmailJob) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *EmailJob) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *EmailJob) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *EmailJob) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_STATUS_UNKNOWN
}

func (x *EmailJob) GetPriority() JobPriority {
	if x != nil {
		return x.Priority
	}
	return JobPriority_PRIORITY_UNKNOWN
}

func (x *EmailJob) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *EmailJob) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *EmailJob) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *EmailJob) GetProcessedAt() string {
	if x != nil {
		return x.ProcessedAt
	}
	return ""
}

func (x *EmailJob) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *EmailJob) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EmailJob) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type EmailTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlTemplate  string                 `protobuf:"bytes,4,opt,name=html_template,json=htmlTemplate,proto3" json:"html_template,omitempty"`
	TextTemplate  string                 `protobuf:"bytes,5,opt,name=text_template,json=textTemplate,proto3" json:"text_template,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailTemplate) Reset() {
	*x = EmailTemplate{}
	mi := &file_email_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTemplate) ProtoMessage() {}

func (x *EmailTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTemplate.ProtoReflect.Descriptor instead.
func (*EmailTemplate) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{23}
}

func (x *EmailTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmailTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmailTemplate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailTemplate) GetHtmlTemplate() string {
	if x != nil {
		return x.HtmlTemplate
	}
	return ""
}

func (x *EmailTemplate) GetTextTemplate() string {
	if x != nil {
		return x.TextTemplate
	}
	return ""
}

func (x *EmailTemplate) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *EmailTemplate) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *EmailTemplate) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EmailTemplate) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type EmailTracking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         int64                  `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	MessageId     string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	SentAt        string                 `protobuf:"bytes,6,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	DeliveredAt   string                 `protobuf:"bytes,7,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	OpenedAt      string                 `protobuf:"bytes,8,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	ClickedAt     string                 `protobuf:"bytes,9,opt,name=clicked_at,json=clickedAt,proto3" json:"clicked_at,omitempty"`
	BounceReason  string                 `protobuf:"bytes,10,opt,name=bounce_reason,json=bounceReason,proto3" json:"bounce_reason,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailTracking) Reset() {
	*x = EmailTracking{}
	mi := &file_email_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTracking) ProtoMessage() {}

func (x *EmailTracking) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTracking.ProtoReflect.Descriptor instead.
func (*EmailTracking) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{24}
}

func (x *EmailTracking) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmailTracking) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *EmailTracking) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EmailTracking) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EmailTracking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EmailTracking) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *EmailTracking) GetDeliveredAt() string {
	if x != nil {
		return x.DeliveredAt
	}
	return ""
}

func (x *EmailTracking) GetOpenedAt() string {
	if x != nil {
		return x.OpenedAt
	}
	return ""
}

func (x *EmailTracking) GetClickedAt() string {
	if x != nil {
		return x.ClickedAt
	}
	return ""
}

func (x *EmailTracking) GetBounceReason() string {
	if x != nil {
		return x.BounceReason
	}
	return ""
}

func (x *EmailTracking) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EmailTracking) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_email_proto protoreflect.FileDescriptor

const file_email_proto_rawDesc = "" +
	"\n" +
	"\vemail.proto\x12\x05email\"\xc8\x02\n" +
	"\x15CreateEmailJobRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x02 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x03 \x03(\tR\x03bcc\x12#\n" +
	"\rtemplate_name\x18\x04 \x01(\tR\ftemplateName\x12I\n" +
	"\tvariables\x18\x05 \x03(\v2+.email.CreateEmailJobRequest.VariablesEntryR\tvariables\x12.\n" +
	"\bpriority\x18\x06 \x01(\x0e2\x12.email.JobPriorityR\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\a \x01(\x05R\n" +
	"maxRetries\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x16CreateEmailJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x03job\x18\x03 \x01(\v2\x0f.email.EmailJobR\x03job\"+\n" +
	"\x12GetEmailJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"l\n" +
	"\x13GetEmailJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x03job\x18\x03 \x01(\v2\x0f.email.EmailJobR\x03job\"\x8a\x01\n" +
	"\x1bUpdateEmailJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x17\n" +
	"\asent_at\x18\x04 \x01(\tR\x06sentAt\"u\n" +
	"\x1cUpdateEmailJobStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x03job\x18\x03 \x01(\v2\x0f.email.EmailJobR\x03job\"\xa2\x01\n" +
	"\x14ListEmailJobsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\bjob_type\x18\x02 \x01(\tR\ajobType\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"\xb0\x01\n" +
	"\x15ListEmailJobsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x04jobs\x18\x03 \x03(\v2\x0f.email.EmailJobR\x04jobs\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"N\n" +
	"\x17GetEmailTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x80\x01\n" +
	"\x18GetEmailTemplateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\btemplate\x18\x03 \x01(\v2\x14.email.EmailTemplateR\btemplate\"b\n" +
	"\x19ListEmailTemplatesRequest\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x9a\x01\n" +
	"\x1aListEmailTemplatesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\ttemplates\x18\x03 \x03(\v2\x14.email.EmailTemplateR\ttemplates\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"\xcb\x01\n" +
	"\x1aCreateEmailTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12!\n" +
	"\fhtml_content\x18\x03 \x01(\tR\vhtmlContent\x12!\n" +
	"\ftext_content\x18\x04 \x01(\tR\vtextContent\x12\x1c\n" +
	"\tvariables\x18\x05 \x01(\tR\tvariables\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"\x83\x01\n" +
	"\x1bCreateEmailTemplateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\btemplate\x18\x03 \x01(\v2\x14.email.EmailTemplateR\btemplate\"\xec\x01\n" +
	"\x1aUpdateEmailTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12!\n" +
	"\fhtml_content\x18\x04 \x01(\tR\vhtmlContent\x12!\n" +
	"\ftext_content\x18\x05 \x01(\tR\vtextContent\x12\x1c\n" +
	"\tvariables\x18\x06 \x01(\tR\tvariables\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"\x83\x01\n" +
	"\x1bUpdateEmailTemplateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\btemplate\x18\x03 \x01(\v2\x14.email.EmailTemplateR\btemplate\"O\n" +
	"\x17GetEmailTrackingRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"\x80\x01\n" +
	"\x18GetEmailTrackingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\btracking\x18\x03 \x01(\v2\x14.email.EmailTrackingR\btracking\"\xa3\x02\n" +
	"\x1aUpdateEmailTrackingRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x17\n" +
	"\asent_at\x18\x05 \x01(\tR\x06sentAt\x12!\n" +
	"\fdelivered_at\x18\x06 \x01(\tR\vdeliveredAt\x12\x1b\n" +
	"\topened_at\x18\a \x01(\tR\bopenedAt\x12\x1d\n" +
	"\n" +
	"clicked_at\x18\b \x01(\tR\tclickedAt\x12#\n" +
	"\rbounce_reason\x18\t \x01(\tR\fbounceReason\"\x83\x01\n" +
	"\x1bUpdateEmailTrackingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\btracking\x18\x03 \x01(\v2\x14.email.EmailTrackingR\btracking\"\x0f\n" +
	"\rHealthRequest\"`\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xa8\x04\n" +
	"\bEmailJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x03 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x04 \x03(\tR\x03bcc\x12#\n" +
	"\rtemplate_name\x18\x05 \x01(\tR\ftemplateName\x12<\n" +
	"\tvariables\x18\x06 \x03(\v2\x1e.email.EmailJob.VariablesEntryR\tvariables\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.email.JobStatusR\x06status\x12.\n" +
	"\bpriority\x18\b \x01(\x0e2\x12.email.JobPriorityR\bpriority\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\n" +
	" \x01(\x05R\n" +
	"maxRetries\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12!\n" +
	"\fprocessed_at\x18\f \x01(\tR\vprocessedAt\x12\x17\n" +
	"\asent_at\x18\r \x01(\tR\x06sentAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x02\n" +
	"\rEmailTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12#\n" +
	"\rhtml_template\x18\x04 \x01(\tR\fhtmlTemplate\x12#\n" +
	"\rtext_template\x18\x05 \x01(\tR\ftextTemplate\x12A\n" +
	"\tvariables\x18\x06 \x03(\v2#.email.EmailTemplate.VariablesEntryR\tvariables\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x02\n" +
	"\rEmailTracking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x03R\x05jobId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x17\n" +
	"\asent_at\x18\x06 \x01(\tR\x06sentAt\x12!\n" +
	"\fdelivered_at\x18\a \x01(\tR\vdeliveredAt\x12\x1b\n" +
	"\topened_at\x18\b \x01(\tR\bopenedAt\x12\x1d\n" +
	"\n" +
	"clicked_at\x18\t \x01(\tR\tclickedAt\x12#\n" +
	"\rbounce_reason\x18\n" +
	" \x01(\tR\fbounceReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt*\x89\x01\n" +
	"\tJobStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x15\n" +
	"\x11STATUS_PROCESSING\x10\x02\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x03\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x04\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x05*]\n" +
	"\vJobPriority\x12\x14\n" +
	"\x10PRIORITY_UNKNOWN\x10\x00\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x032\xa6\a\n" +
	"\fEmailService\x12M\n" +
	"\x0eCreateEmailJob\x12\x1c.email.CreateEmailJobRequest\x1a\x1d.email.CreateEmailJobResponse\x12D\n" +
	"\vGetEmailJob\x12\x19.email.GetEmailJobRequest\x1a\x1a.email.GetEmailJobResponse\x12_\n" +
	"\x14UpdateEmailJobStatus\x12\".email.UpdateEmailJobStatusRequest\x1a#.email.UpdateEmailJobStatusResponse\x12J\n" +
	"\rListEmailJobs\x12\x1b.email.ListEmailJobsRequest\x1a\x1c.email.ListEmailJobsResponse\x12S\n" +
	"\x10GetEmailTemplate\x12\x1e.email.GetEmailTemplateRequest\x1a\x1f.email.GetEmailTemplateResponse\x12Y\n" +
	"\x12ListEmailTemplates\x12 .email.ListEmailTemplatesRequest\x1a!.email.ListEmailTemplatesResponse\x12\\\n" +
	"\x13CreateEmailTemplate\x12!.email.CreateEmailTemplateRequest\x1a\".email.CreateEmailTemplateResponse\x12\\\n" +
	"\x13UpdateEmailTemplate\x12!.email.UpdateEmailTemplateRequest\x1a\".email.UpdateEmailTemplateResponse\x12S\n" +
	"\x10GetEmailTracking\x12\x1e.email.GetEmailTrackingRequest\x1a\x1f.email.GetEmailTrackingResponse\x12\\\n" +
	"\x13UpdateEmailTracking\x12!.email.UpdateEmailTrackingRequest\x1a\".email.UpdateEmailTrackingResponse\x125\n" +
	"\x06Health\x12\x14.email.HealthRequest\x1a\x15.email.HealthResponseB-Z+booking-system/email-worker/internal/protosb\x06proto3"

var (
	file_email_proto_rawDescOnce sync.Once
	file_email_proto_rawDescData []byte
)

func file_email_proto_rawDescGZIP() []byte {
	file_email_proto_rawDescOnce.Do(func() {
		file_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)))
	})
	return file_email_proto_rawDescData
}

var file_email_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_email_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_email_proto_goTypes = []any{
	(JobStatus)(0),                       // 0: email.JobStatus
	(JobPriority)(0),                     // 1: email.JobPriority
	(*CreateEmailJobRequest)(nil),        // 2: email.CreateEmailJobRequest
	(*CreateEmailJobResponse)(nil),       // 3: email.CreateEmailJobResponse
	(*GetEmailJobRequest)(nil),           // 4: email.GetEmailJobRequest
	(*GetEmailJobResponse)(nil),          // 5: email.GetEmailJobResponse
	(*UpdateEmailJobStatusRequest)(nil),  // 6: email.UpdateEmailJobStatusRequest
	(*UpdateEmailJobStatusResponse)(nil), // 7: email.UpdateEmailJobStatusResponse
	(*ListEmailJobsRequest)(nil),         // 8: email.ListEmailJobsRequest
	(*ListEmailJobsResponse)(nil),        // 9: email.ListEmailJobsResponse
	(*GetEmailTemplateRequest)(nil),      // 10: email.GetEmailTemplateRequest
	(*GetEmailTemplateResponse)(nil),     // 11: email.GetEmailTemplateResponse
	(*ListEmailTemplatesRequest)(nil),    // 12: email.ListEmailTemplatesRequest
	(*ListEmailTemplatesResponse)(nil),   // 13: email.ListEmailTemplatesResponse
	(*CreateEmailTemplateRequest)(nil),   // 14: email.CreateEmailTemplateRequest
	(*CreateEmailTemplateResponse)(nil),  // 15: email.CreateEmailTemplateResponse
	(*UpdateEmailTemplateRequest)(nil),   // 16: email.UpdateEmailTemplateRequest
	(*UpdateEmailTemplateResponse)(nil),  // 17: email.UpdateEmailTemplateResponse
	(*GetEmailTrackingRequest)(nil),      // 18: email.GetEmailTrackingRequest
	(*GetEmailTrackingResponse)(nil),     // 19: email.GetEmailTrackingResponse
	(*UpdateEmailTrackingRequest)(nil),   // 20: email.UpdateEmailTrackingRequest
	(*UpdateEmailTrackingResponse)(nil),  // 21: email.UpdateEmailTrackingResponse
	(*HealthRequest)(nil),                // 22: email.HealthRequest
	(*HealthResponse)(nil),               // 23: email.HealthResponse
	(*EmailJob)(nil),                     // 24: email.EmailJob
	(*EmailTemplate)(nil),                // 25: email.EmailTemplate
	(*EmailTracking)(nil),                // 26: email.EmailTracking
	nil,                                  // 27: email.CreateEmailJobRequest.VariablesEntry
	nil,                                  // 28: email.EmailJob.VariablesEntry
	nil,                                  // 29: email.EmailTemplate.VariablesEntry
}
var file_email_proto_depIdxs = []int32{
	27, // 0: email.CreateEmailJobRequest.variables:type_name -> email.CreateEmailJobRequest.VariablesEntry
	1,  // 1: email.CreateEmailJobRequest.priority:type_name -> email.JobPriority
	24, // 2: email.CreateEmailJobResponse.job:type_name -> email.EmailJob
	24, // 3: email.GetEmailJobResponse.job:type_name -> email.EmailJob
	24, // 4: email.UpdateEmailJobStatusResponse.job:type_name -> email.EmailJob
	24, // 5: email.ListEmailJobsResponse.jobs:type_name -> email.EmailJob
	25, // 6: email.GetEmailTemplateResponse.template:type_name -> email.EmailTemplate
	25, // 7: email.ListEmailTemplatesResponse.templates:type_name -> email.EmailTemplate
	25, // 8: email.CreateEmailTemplateResponse.template:type_name -> email.EmailTemplate
	25, // 9: email.UpdateEmailTemplateResponse.template:type_name -> email.EmailTemplate
	26, // 10: email.GetEmailTrackingResponse.tracking:type_name -> email.EmailTracking
	26, // 11: email.UpdateEmailTrackingResponse.tracking:type_name -> email.EmailTracking
	28, // 12: email.EmailJob.variables:type_name -> email.EmailJob.VariablesEntry
	0,  // 13: email.EmailJob.status:type_name -> email.JobStatus
	1,  // 14: email.EmailJob.priority:type_name -> email.JobPriority
	29, // 15: email.EmailTemplate.variables:type_name -> email.EmailTemplate.VariablesEntry
	2,  // 16: email.EmailService.CreateEmailJob:input_type -> email.CreateEmailJobRequest
	4,  // 17: email.EmailService.GetEmailJob:input_type -> email.GetEmailJobRequest
	6,  // 18: email.EmailService.UpdateEmailJobStatus:input_type -> email.UpdateEmailJobStatusRequest
	8,  // 19: email.EmailService.ListEmailJobs:input_type -> email.ListEmailJobsRequest
	10, // 20: email.EmailService.GetEmailTemplate:input_type -> email.GetEmailTemplateRequest
	12, // 21: email.EmailService.ListEmailTemplates:input_type -> email.ListEmailTemplatesRequest
	14, // 22: email.EmailService.CreateEmailTemplate:input_type -> email.CreateEmailTemplateRequest
	16, // 23: email.EmailService.UpdateEmailTemplate:input_type -> email.UpdateEmailTemplateRequest
	18, // 24: email.EmailService.GetEmailTracking:input_type -> email.GetEmailTrackingRequest
	20, // 25: email.EmailService.UpdateEmailTracking:input_type -> email.UpdateEmailTrackingRequest
	22, // 26: email.EmailService.Health:input_type -> email.HealthRequest
	3,  // 27: email.EmailService.CreateEmailJob:output_type -> email.CreateEmailJobResponse
	5,  // 28: email.EmailService.GetEmailJob:output_type -> email.GetEmailJobResponse
	7,  // 29: email.EmailService.UpdateEmailJobStatus:output_type -> email.UpdateEmailJobStatusResponse
	9,  // 30: email.EmailService.ListEmailJobs:output_type -> email.ListEmailJobsResponse
	11, // 31: email.EmailService.GetEmailTemplate:output_type -> email.GetEmailTemplateResponse
	13, // 32: email.EmailService.ListEmailTemplates:output_type -> email.ListEmailTemplatesResponse
	15, // 33: email.EmailService.CreateEmailTemplate:output_type -> email.CreateEmailTemplateResponse
	17, // 34: email.EmailService.UpdateEmailTemplate:output_type -> email.UpdateEmailTemplateResponse
	19, // 35: email.EmailService.GetEmailTracking:output_type -> email.GetEmailTrackingResponse
	21, // 36: email.EmailService.UpdateEmailTracking:output_type -> email.UpdateEmailTrackingResponse
	23, // 37: email.EmailService.Health:output_type -> email.HealthResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_email_proto_init() }
func file_email_proto_init() {
	if File_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_proto_goTypes,
		DependencyIndexes: file_email_proto_depIdxs,
		EnumInfos:         file_email_proto_enumTypes,
		MessageInfos:      file_email_proto_msgTypes,
	}.Build()
	File_email_proto = out.File
	file_email_proto_goTypes = nil
	file_email_proto_depIdxs = nil
}
